#!/bin/bash

# ==============================================================================
#
# --- Name ---
#
# Description:
# Author: Sergiy Noskov <sergiy@noskov.org>
# Version: 1.0.0
# License: MIT License
# Style Guide: Follows Google's Shell Style Guide
# Usage:
# References:
#   - https://google.github.io/styleguide/shellguide.html
#
# ==============================================================================

# ==============================================================================
# --- Name ---
#
# Description of the function.
#
# Globals:
#   List of global variables used and modified.
# Arguments:
#   $1 - Arguments taken.
# Outputs:
#   Output to STDOUT or STDERR.
# Returns:
#   Returned values other than the default exit status of the last command run.
# ==============================================================================





exit 0
